# Generated by Django 2.1.2 on 2018-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNick', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userRun', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('fecNac', models.DateTimeField(null=True)),
                ('userFono', models.IntegerField(max_length=15, null=True)),
                ('userRegion', models.CharField(max_length=30)),
                ('userComuna', models.CharField(max_length=30)),
                ('userTipo', models.CharField(max_length=30)),
            ],
        ),
    ]
