# Generated by Django 2.1.2 on 2018-11-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
